import React, { useState, useEffect, useMemo } from 'react';
import { 
  RefreshCw, Sparkles, BrainCircuit, Quote, Zap, AlertTriangle, Fingerprint, 
  RotateCw, Briefcase, Share2, Check, PieChart, Activity, Thermometer, Heart, 
  ArrowLeft, Layers, TrendingUp, Battery
} from 'lucide-react';
import { MemoryEntry, UserProfile } from '../types';
import { generateUserProfile } from '../services/geminiService';

interface ProfileViewProps {
  entries: MemoryEntry[];
}

type AnalysisViewType = 'MAIN' | 'COMPOSITION' | 'MOOD' | 'STRESS' | 'HOBBY';

export const ProfileView: React.FC<ProfileViewProps> = ({ entries }) => {
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [isLoadingProfile, setIsLoadingProfile] = useState(false);
  const [isFlipped, setIsFlipped] = useState(false);
  const [personaMode, setPersonaMode] = useState<'witty' | 'formal'>('witty');
  const [hasCopied, setHasCopied] = useState(false);
  
  // Navigation State
  const [currentView, setCurrentView] = useState<AnalysisViewType>('MAIN');

  // --- Core Profile Logic ---
  const refreshProfile = async (targetMode?: 'witty' | 'formal') => {
    if (entries.length === 0) return;
    const modeToUse = targetMode || personaMode;
    setIsLoadingProfile(true);
    setIsFlipped(false);
    try {
      const data = await generateUserProfile(entries, modeToUse);
      setProfile(data);
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoadingProfile(false);
    }
  };

  const handleToggleMode = () => {
      const newMode = personaMode === 'witty' ? 'formal' : 'witty';
      setPersonaMode(newMode);
      refreshProfile(newMode);
  };

  const handleShare = () => {
      if (!profile) return;
      const text = `【${profile.archetype}】\n\n"${profile.summary}"\n\n(Generated by Go2Grow)`;
      navigator.clipboard.writeText(text).then(() => {
          setHasCopied(true);
          setTimeout(() => setHasCopied(false), 2000);
      });
  };

  useEffect(() => {
    if (entries.length > 0 && !profile) refreshProfile();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- Analysis Logic Helper ---
  // Memoize calculations to avoid re-running on every render
  const analysisData = useMemo(() => {
      if (entries.length === 0) return null;

      // 1. Composition (Tag Frequency)
      const tagCounts: Record<string, number> = {};
      entries.forEach(e => e.tags.forEach(t => tagCounts[t] = (tagCounts[t] || 0) + 1));
      const sortedTags = Object.entries(tagCounts)
          .sort(([,a], [,b]) => b - a)
          .slice(0, 5) // Top 5
          .map(([tag, count]) => ({ tag, count, percent: Math.round((count / entries.length) * 100) }));

      // 2. Mood Trend (Last 14 entries sorted by time)
      const moodHistory = [...entries]
          .sort((a, b) => a.timestamp - b.timestamp)
          .slice(-14)
          .map(e => ({ val: e.userMood || 50, date: new Date(e.timestamp).getDate() }));

      // 3. Stress System (Inverse of mood + High Importance + Negative keywords)
      // Heuristic: Low mood (<40) + "High" importance increases stress score
      const recentEntries = entries.slice(0, 10);
      let stressScore = 0;
      recentEntries.forEach(e => {
          const mood = e.userMood || 50;
          if (mood < 40) stressScore += 15;
          if (e.importance === 'high') stressScore += 10;
          if (e.tags.includes('工作') || e.tags.includes('压力') || e.tags.includes('deadline')) stressScore += 5;
      });
      // Normalize to 0-100 (approximate)
      const stressLevel = Math.min(100, Math.max(0, Math.round(stressScore / recentEntries.length * 10))); 

      // 4. Hobby Analysis (High Mood Tags)
      const happyEntries = entries.filter(e => (e.userMood || 50) > 70);
      const happyTags: Record<string, number> = {};
      happyEntries.forEach(e => e.tags.forEach(t => happyTags[t] = (happyTags[t] || 0) + 1));
      const hobbies = Object.entries(happyTags)
          .sort(([,a], [,b]) => b - a)
          .slice(0, 8)
          .map(([tag]) => tag);

      return { sortedTags, moodHistory, stressLevel, hobbies };
  }, [entries]);


  // --- Empty State ---
  if (!profile && !isLoadingProfile && entries.length === 0) {
      return (
          <div className="max-w-4xl mx-auto flex flex-col items-center justify-center min-h-[50vh] text-center p-6">
              <Fingerprint size={64} className="text-slate-700 mb-4" />
              <h2 className="text-xl font-light text-slate-300">尚未收集到足够的行为样本</h2>
              <p className="text-slate-500 mt-2">请先去记录一些生活碎片，AI 侧写师正在待命。</p>
          </div>
      )
  }

  // --- Sub-View Renderers ---
  const renderCompositionView = () => (
      <div className="space-y-6 animate-fadeIn">
          <div className="bg-gradient-to-br from-indigo-900/20 to-slate-900/50 p-6 rounded-2xl border border-indigo-500/20">
              <h3 className="text-sm font-bold text-indigo-300 uppercase tracking-widest mb-6 flex items-center gap-2">
                  <Layers size={16} /> 生活成分分析
              </h3>
              <div className="space-y-5">
                  {analysisData?.sortedTags.map((item, idx) => (
                      <div key={idx} className="group">
                          <div className="flex justify-between text-xs mb-1.5">
                              <span className="text-slate-200 font-medium">{item.tag}</span>
                              <span className="text-slate-500 font-mono">{item.percent}%</span>
                          </div>
                          <div className="h-3 w-full bg-black/40 rounded-full overflow-hidden border border-white/5">
                              <div 
                                  className="h-full bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full transition-all duration-1000 ease-out group-hover:brightness-125"
                                  style={{ width: `${item.percent}%`, transitionDelay: `${idx * 100}ms` }}
                              ></div>
                          </div>
                      </div>
                  ))}
              </div>
              <p className="mt-8 text-xs text-slate-500 italic text-center">
                  * 基于您的标签使用频率生成的成分表
              </p>
          </div>
      </div>
  );

  const renderMoodView = () => {
      const data = analysisData?.moodHistory || [];
      const width = 100;
      const height = 40;
      // Generate SVG path
      const points = data.map((d, i) => {
          const x = (i / (data.length - 1)) * width;
          const y = height - (d.val / 100) * height;
          return `${x},${y}`;
      }).join(' ');

      const avgMood = Math.round(data.reduce((a, b) => a + b.val, 0) / data.length) || 0;

      return (
          <div className="space-y-6 animate-fadeIn">
              <div className="bg-gradient-to-br from-emerald-900/20 to-slate-900/50 p-6 rounded-2xl border border-emerald-500/20">
                  <div className="flex justify-between items-start mb-6">
                      <h3 className="text-sm font-bold text-emerald-300 uppercase tracking-widest flex items-center gap-2">
                          <Activity size={16} /> 情绪心电图
                      </h3>
                      <div className="text-right">
                          <div className="text-2xl font-bold text-white">{avgMood}</div>
                          <div className="text-[10px] text-slate-500 uppercase">Avg Score</div>
                      </div>
                  </div>

                  <div className="relative h-48 w-full bg-black/20 rounded-xl border border-white/5 p-4 flex items-end">
                      {/* Grid Lines */}
                      <div className="absolute inset-0 flex flex-col justify-between p-4 opacity-20 pointer-events-none">
                          <div className="w-full h-[1px] bg-slate-500"></div>
                          <div className="w-full h-[1px] bg-slate-500"></div>
                          <div className="w-full h-[1px] bg-slate-500"></div>
                      </div>

                      {/* SVG Chart */}
                      <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full overflow-visible" preserveAspectRatio="none">
                          <defs>
                              <linearGradient id="moodGradient" x1="0" y1="0" x2="0" y2="1">
                                  <stop offset="0%" stopColor="#34d399" stopOpacity="0.8"/>
                                  <stop offset="100%" stopColor="#34d399" stopOpacity="0"/>
                              </linearGradient>
                          </defs>
                          {/* Fill Area */}
                          <path 
                             d={`M0,${height} ${points} L${width},${height} Z`} 
                             fill="url(#moodGradient)" 
                             opacity="0.3" 
                             className="animate-fadeIn"
                          />
                          {/* Stroke Line */}
                          <polyline 
                              points={points} 
                              fill="none" 
                              stroke="#34d399" 
                              strokeWidth="0.8" 
                              vectorEffect="non-scaling-stroke"
                              strokeLinecap="round"
                              className="drop-shadow-[0_0_8px_rgba(52,211,153,0.5)]"
                          />
                          {/* Dots */}
                          {data.map((d, i) => {
                              const x = (i / (data.length - 1)) * width;
                              const y = height - (d.val / 100) * height;
                              return (
                                  <circle key={i} cx={x} cy={y} r="1.5" fill="#10b981" className="hover:r-3 transition-all" />
                              );
                          })}
                      </svg>
                  </div>
                  <p className="mt-4 text-xs text-slate-400 text-center">
                      最近 {data.length} 个情绪采样点
                  </p>
              </div>
          </div>
      );
  };

  const renderStressView = () => {
      const level = analysisData?.stressLevel || 0;
      let color = "text-emerald-400";
      let status = "系统正常";
      if (level > 40) { color = "text-amber-400"; status = "轻度负载"; }
      if (level > 70) { color = "text-rose-500"; status = "过热预警"; }

      return (
          <div className="space-y-6 animate-fadeIn">
              <div className="bg-gradient-to-br from-rose-900/20 to-slate-900/50 p-6 rounded-2xl border border-rose-500/20 text-center">
                  <h3 className="text-sm font-bold text-rose-300 uppercase tracking-widest mb-8 flex items-center justify-center gap-2">
                      <Thermometer size={16} /> 压力监测系统
                  </h3>
                  
                  <div className="relative w-48 h-48 mx-auto mb-6 flex items-center justify-center">
                      {/* Circular Gauge Background */}
                      <div className="absolute inset-0 rounded-full border-8 border-slate-800"></div>
                      {/* Active Arc (Simulated with Conic Gradient) */}
                      <div 
                          className="absolute inset-0 rounded-full border-8 border-transparent transition-all duration-1000"
                          style={{
                              background: `conic-gradient(from 180deg, ${level > 70 ? '#f43f5e' : (level > 40 ? '#fbbf24' : '#34d399')} ${level * 3.6}deg, transparent 0deg)`,
                              mask: 'radial-gradient(transparent 64%, black 65%)',
                              WebkitMask: 'radial-gradient(transparent 64%, black 65%)'
                          }}
                      ></div>
                      
                      <div className="flex flex-col items-center">
                          <span className={`text-4xl font-black ${color}`}>{level}%</span>
                          <span className="text-xs text-slate-500 mt-1 uppercase">Load</span>
                      </div>
                  </div>

                  <div className={`inline-block px-4 py-2 rounded-lg bg-black/40 border border-white/5 ${color}`}>
                      <span className="text-xs font-bold tracking-widest uppercase">{status}</span>
                  </div>
                  
                  <p className="mt-8 text-xs text-slate-500 leading-relaxed px-4">
                      * 压力指数基于低情绪记录频率及高重要性事项密度计算。
                  </p>
              </div>
          </div>
      );
  };

  const renderHobbyView = () => (
      <div className="space-y-6 animate-fadeIn">
          <div className="bg-gradient-to-br from-pink-900/20 to-slate-900/50 p-6 rounded-2xl border border-pink-500/20">
              <h3 className="text-sm font-bold text-pink-300 uppercase tracking-widest mb-6 flex items-center gap-2">
                  <Heart size={16} /> 高能活动分析
              </h3>
              
              <p className="text-xs text-slate-400 mb-6">
                  这些活动通常伴随着高于 70 分的心情指数，是你的“能量加油站”。
              </p>

              <div className="flex flex-wrap gap-3 justify-center">
                  {analysisData?.hobbies.length === 0 ? (
                      <div className="text-slate-500 text-sm italic py-8">
                          暂无高能数据，请多记录快乐时刻。
                      </div>
                  ) : (
                      analysisData?.hobbies.map((tag, i) => (
                          <div 
                              key={i}
                              className="px-4 py-2 rounded-full bg-pink-500/10 border border-pink-500/20 text-pink-200 text-sm animate-float"
                              style={{ animationDelay: `${i * 0.2}s`, animationDuration: `${3 + i}s` }}
                          >
                              #{tag}
                          </div>
                      ))
                  )}
              </div>
          </div>
      </div>
  );

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn pb-20 perspective-1000">
      
      {/* HEADER Area */}
      <div className="mb-4 text-center md:text-left border-b border-white/5 pb-4 flex justify-between items-end">
        <div>
          {currentView === 'MAIN' ? (
              <>
                <h2 className="text-2xl font-light text-slate-100">人格侧写</h2>
                <p className="text-slate-500 text-sm mt-1">基于行为数据的深度解析。</p>
              </>
          ) : (
              <button 
                onClick={() => setCurrentView('MAIN')}
                className="group flex items-center gap-2 text-indigo-400 hover:text-white transition-colors"
              >
                  <div className="p-1.5 rounded-full bg-indigo-500/10 group-hover:bg-indigo-500/30">
                      <ArrowLeft size={16} />
                  </div>
                  <div className="flex flex-col items-start">
                    <span className="text-xs font-bold uppercase tracking-widest text-slate-500 group-hover:text-slate-300">Back</span>
                    <span className="text-sm font-medium">返回全息画像</span>
                  </div>
              </button>
          )}
        </div>
        
        {/* Only show top actions in MAIN view */}
        {currentView === 'MAIN' && (
            <div className="flex items-center gap-2">
                <button 
                    onClick={() => refreshProfile()}
                    disabled={isLoadingProfile}
                    className="w-9 h-9 flex items-center justify-center bg-white/5 text-slate-400 rounded-full hover:bg-white/10 hover:text-white transition-all border border-white/5 disabled:opacity-50"
                >
                    <RefreshCw size={16} className={isLoadingProfile ? "animate-spin" : ""} />
                </button>
                <button 
                    onClick={handleToggleMode}
                    disabled={isLoadingProfile}
                    className={`w-9 h-9 flex items-center justify-center rounded-full transition-all border disabled:opacity-50
                        ${personaMode === 'witty' 
                            ? 'bg-indigo-600/20 text-indigo-300 border-indigo-500/30 hover:bg-indigo-600/30' 
                            : 'bg-emerald-600/20 text-emerald-300 border-emerald-500/30 hover:bg-emerald-600/30'}`}
                >
                    {personaMode === 'witty' ? <Sparkles size={16} /> : <Briefcase size={16} />}
                </button>
                <button 
                    onClick={handleShare}
                    disabled={isLoadingProfile || !profile}
                    className="w-9 h-9 flex items-center justify-center bg-white/5 text-slate-400 rounded-full hover:bg-white/10 hover:text-white transition-all border border-white/5"
                >
                    {hasCopied ? <Check size={16} className="text-green-400" /> : <Share2 size={16} />}
                </button>
            </div>
        )}
      </div>

      {/* === CONTENT SWITCHER === */}
      {currentView === 'MAIN' ? (
        <>
            {/* 3D Card Container */}
            <div className="relative w-full max-w-md mx-auto aspect-[3/4] md:aspect-[3/2] lg:aspect-[16/9] min-h-[480px]">
                <div 
                    className={`w-full h-full transition-all duration-700 transform-style-3d cursor-pointer ${isFlipped ? 'rotate-y-180' : ''}`}
                    onClick={() => !isLoadingProfile && setIsFlipped(!isFlipped)}
                >
                    {/* ... FRONT SIDE (Same as before) ... */}
                    <div className={`absolute inset-0 w-full h-full backface-hidden rounded-2xl border border-white/10 shadow-[0_0_50px_rgba(0,0,0,0.3)] overflow-hidden
                        ${personaMode === 'witty' ? 'bg-gradient-to-br from-[#1e1b4b] to-[#0f172a]' : 'bg-gradient-to-br from-[#0f172a] to-[#141414]'}`}
                    >
                        <div className={`absolute top-0 right-0 w-64 h-64 rounded-full blur-[80px] pointer-events-none 
                            ${personaMode === 'witty' ? 'bg-indigo-500/10' : 'bg-emerald-500/5'}`}></div>
                        <div className="absolute bottom-0 left-0 w-48 h-48 bg-emerald-500/5 rounded-full blur-[60px] pointer-events-none"></div>
                        
                        <div className="absolute top-4 right-4 text-xs font-mono text-slate-600 border border-slate-700/50 px-2 py-1 rounded">
                            ID: {profile?.recentMood || "ANALYZING"}
                        </div>
                        
                        {isLoadingProfile ? (
                            <div className="w-full h-full flex flex-col items-center justify-center gap-6">
                                <div className="relative">
                                    <div className="absolute inset-0 bg-indigo-500/20 blur-xl rounded-full animate-pulse"></div>
                                    <BrainCircuit size={64} className="text-indigo-400 relative z-10 animate-float" />
                                </div>
                                <p className="text-indigo-200/50 font-mono tracking-widest text-sm animate-pulse">
                                    NEURAL SCANNING...
                                </p>
                            </div>
                        ) : (
                            <div className="p-8 h-full flex flex-col justify-between relative z-10">
                                <div className="text-center mt-8">
                                    <div className="inline-block mb-3">
                                        {personaMode === 'witty' 
                                            ? <Sparkles size={32} className="text-amber-400 mx-auto animate-pulse-slow" />
                                            : <Briefcase size={32} className="text-emerald-400 mx-auto" />
                                        }
                                    </div>
                                    <h3 className="text-xs font-bold tracking-[0.3em] text-slate-400 uppercase mb-2">
                                        {personaMode === 'witty' ? "DETECTED ARCHETYPE" : "PROFESSIONAL PROFILE"}
                                    </h3>
                                    <h1 className="text-3xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-indigo-200 via-white to-indigo-200 tracking-tight leading-tight glitch-text" data-text={profile?.archetype}>
                                        {profile?.archetype || "未知生物"}
                                    </h1>
                                </div>

                                <div className="relative my-6">
                                    {personaMode === 'witty' && <Quote size={40} className="absolute -top-4 -left-2 text-white/5 transform -scale-x-100" />}
                                    <p className={`text-lg md:text-xl font-medium text-center leading-relaxed px-4
                                        ${personaMode === 'witty' ? 'text-indigo-100 italic' : 'text-slate-200 font-light'}`}>
                                        {personaMode === 'witty' ? `"${profile?.summary}"` : profile?.summary}
                                    </p>
                                    {personaMode === 'witty' && <Quote size={40} className="absolute -bottom-4 -right-2 text-white/5" />}
                                </div>

                                <div className="grid grid-cols-2 gap-4 mt-auto">
                                    <div className="bg-emerald-900/10 border border-emerald-500/10 rounded-xl p-3 backdrop-blur-sm">
                                        <h4 className="flex items-center gap-2 text-[10px] font-bold text-emerald-500 uppercase tracking-widest mb-2">
                                            <Zap size={12} /> {personaMode === 'witty' ? "核心成分" : "核心优势"}
                                        </h4>
                                        <div className="flex flex-wrap gap-2">
                                            {profile?.strengths?.slice(0, 3).map((s, i) => (
                                                <span key={i} className="text-xs text-emerald-200/80 bg-emerald-500/10 px-2 py-1 rounded">
                                                    {s}
                                                </span>
                                            ))}
                                        </div>
                                    </div>

                                    <div className="bg-rose-900/10 border border-rose-500/10 rounded-xl p-3 backdrop-blur-sm">
                                        <h4 className="flex items-center gap-2 text-[10px] font-bold text-rose-500 uppercase tracking-widest mb-2">
                                            <AlertTriangle size={12} /> {personaMode === 'witty' ? "副作用" : "发展建议"}
                                        </h4>
                                        <div className="flex flex-wrap gap-2">
                                            {profile?.areasForImprovement?.slice(0, 3).map((s, i) => (
                                                <span key={i} className="text-xs text-rose-200/80 bg-rose-500/10 px-2 py-1 rounded">
                                                    {s}
                                                </span>
                                            ))}
                                        </div>
                                    </div>
                                </div>

                                <div className="absolute bottom-4 right-1/2 transform translate-x-1/2 text-[10px] text-slate-500 flex items-center gap-1 animate-bounce">
                                    <RotateCw size={10} />
                                    点击翻转查看{personaMode === 'witty' ? "真相" : "详情"}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* ... BACK SIDE (Same as before) ... */}
                    <div className="absolute inset-0 w-full h-full backface-hidden rotate-y-180 bg-[#1e293b] rounded-2xl border border-white/10 shadow-2xl p-8 overflow-y-auto custom-scrollbar flex flex-col">
                        <div className={`absolute top-0 left-0 w-full h-1 bg-gradient-to-r 
                            ${personaMode === 'witty' ? 'from-indigo-500 via-purple-500 to-pink-500' : 'from-slate-500 via-emerald-500 to-cyan-500'}`}>
                        </div>
                        
                        <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-6 flex items-center gap-2">
                            <Fingerprint size={16} /> 深度档案解密
                        </h3>

                        <div className="prose prose-invert prose-sm max-w-none">
                            <p className={`leading-relaxed text-base border-l-2 pl-4 mb-8
                                ${personaMode === 'witty' ? 'text-slate-300 font-light border-indigo-500/30' : 'text-slate-200 border-emerald-500/30'}`}>
                                {profile?.detailedAnalysis || profile?.summary}
                            </p>

                            <div className="bg-black/20 rounded-xl p-5 border border-white/5 space-y-4">
                                <div>
                                    <h4 className="text-indigo-400 font-bold mb-2 text-xs uppercase">诊断报告</h4>
                                    <p className="text-xs text-slate-400">
                                        检测到用户近期情绪状态为 <span className="text-white font-bold">{profile?.recentMood}</span>。
                                        {personaMode === 'witty' 
                                            ? " 建议适当调整生活节奏，或者... 继续保持，反正 AI 也管不了你。"
                                            : " 建议您关注上述发展领域，保持优势，逐步优化生活节奏。"
                                        }
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div className="mt-auto pt-8 text-center">
                            <button className="text-xs text-slate-500 hover:text-white transition-colors flex items-center justify-center gap-2 mx-auto w-full py-4">
                                <RotateCw size={12} /> 返回正面
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* NEW: 4-Button Analysis Grid */}
            <div className="max-w-md mx-auto mt-8 grid grid-cols-2 gap-4">
                <button 
                  onClick={() => setCurrentView('COMPOSITION')}
                  className="group flex flex-col items-center justify-center gap-3 bg-[#0f172a]/60 backdrop-blur-md border border-white/5 rounded-2xl p-6 hover:bg-indigo-900/20 hover:border-indigo-500/30 hover:shadow-lg transition-all"
                >
                    <div className="p-3 rounded-full bg-indigo-500/10 text-indigo-400 group-hover:scale-110 transition-transform">
                        <PieChart size={20} />
                    </div>
                    <span className="text-xs font-bold text-slate-400 group-hover:text-indigo-200 uppercase tracking-wider">生活构成</span>
                </button>

                <button 
                  onClick={() => setCurrentView('MOOD')}
                  className="group flex flex-col items-center justify-center gap-3 bg-[#0f172a]/60 backdrop-blur-md border border-white/5 rounded-2xl p-6 hover:bg-emerald-900/20 hover:border-emerald-500/30 hover:shadow-lg transition-all"
                >
                    <div className="p-3 rounded-full bg-emerald-500/10 text-emerald-400 group-hover:scale-110 transition-transform">
                        <TrendingUp size={20} />
                    </div>
                    <span className="text-xs font-bold text-slate-400 group-hover:text-emerald-200 uppercase tracking-wider">情绪趋势</span>
                </button>

                <button 
                  onClick={() => setCurrentView('STRESS')}
                  className="group flex flex-col items-center justify-center gap-3 bg-[#0f172a]/60 backdrop-blur-md border border-white/5 rounded-2xl p-6 hover:bg-rose-900/20 hover:border-rose-500/30 hover:shadow-lg transition-all"
                >
                    <div className="p-3 rounded-full bg-rose-500/10 text-rose-400 group-hover:scale-110 transition-transform">
                        <Battery size={20} />
                    </div>
                    <span className="text-xs font-bold text-slate-400 group-hover:text-rose-200 uppercase tracking-wider">压力系统</span>
                </button>

                <button 
                  onClick={() => setCurrentView('HOBBY')}
                  className="group flex flex-col items-center justify-center gap-3 bg-[#0f172a]/60 backdrop-blur-md border border-white/5 rounded-2xl p-6 hover:bg-pink-900/20 hover:border-pink-500/30 hover:shadow-lg transition-all"
                >
                    <div className="p-3 rounded-full bg-pink-500/10 text-pink-400 group-hover:scale-110 transition-transform">
                        <Heart size={20} />
                    </div>
                    <span className="text-xs font-bold text-slate-400 group-hover:text-pink-200 uppercase tracking-wider">爱好分析</span>
                </button>
            </div>
        </>
      ) : (
        /* === DETAIL VIEW CONTAINER === */
        <div className="max-w-2xl mx-auto min-h-[500px] flex flex-col">
            <div className="flex-1">
                {currentView === 'COMPOSITION' && renderCompositionView()}
                {currentView === 'MOOD' && renderMoodView()}
                {currentView === 'STRESS' && renderStressView()}
                {currentView === 'HOBBY' && renderHobbyView()}
            </div>
        </div>
      )}

      <style>{`
        .perspective-1000 { perspective: 1000px; }
        .transform-style-3d { transform-style: preserve-3d; }
        .backface-hidden { backface-visibility: hidden; }
        .rotate-y-180 { transform: rotateY(180deg); }
      `}</style>
    </div>
  );
};
